//Updates
function PS4Update(){ window.open("https://mega.nz/folder/aUxD0L4L#la4NaqIURDRFvgnMHtIlbw");}
function PS4UpdateWeb(){ window.open("https://www.playstation.com/es-cl/support/hardware/ps4/system-software/");}
function PS4UpdateWebAllWeb(){ window.open("https://darthsternie.net/ps4-firmwares/");}
//Liberar
function USB900(){ window.open("https://mega.nz/folder/KY4hAISY#S3eo7XFGwx1HYH3fAVYyBw");}
function USB900Web(){ window.open("https://github.com/ChendoChap/pOOBs4");}
function ExploitDisco(){ window.open("https://mega.nz/folder/DIAnQDhD#ABu6LFmaBnmA1efL3kb0GQ");}
function ExploitDiscoWeb(){ window.open("https://github.com/Gezine/BD-JB-1250");}
//Payload
function PayloadsPKG(){ window.open("https://mega.nz/file/vEwCVTYI#oLzZOJTFiJfRzQzSSxE3-4e7rqub1m6nYeHA6f8mtT4");}
function AllPayloads(){ window.open("https://mega.nz/folder/iBgxkZCS#XK_WH8E8GJzWno5BJ86qgw");}
function ProgramaPC(){ window.open("https://mega.nz/folder/KIQkATyA#1hjXUYGTC8NVKiAP4F959g");}
function PayloadsWeb(){ window.open("https://github.com/Al-Azif/ps4-payload-guest");}
function LogMeinHamachi(){ window.open("https://mega.nz/folder/zMwHBZxR#vjKEhTAs4Bu0b5sYyY_9Hg");}
function LogMeinHamachiWeb(){ window.open("https://github.com/sleirsgoevy/ps4-hamachi/releases");}
function ICONMASK(){ window.open("https://mega.nz/folder/jJZSya4a#5ZubB9DvA9nxWsOe8rT9tQ");}
function ICONMASKWeb(){ window.open("https://pkg-zone.com/details/LAPY20007");}
function Temperature(){ window.open("https://mega.nz/folder/7NQ2xA6a#0gIfp0YGgvnvtzxq5YKyhQ");}
function TemperatureWeb(){ window.open("https://pkg-zone.com/details/LAPY20006");}
function PatchInstaller(){ window.open("https://mega.nz/folder/GYwV1D6L#WWJ-8tUC4wf7wmii4sxr7w");}
function PatchInstallerWeb(){ window.open("https://orbispatches.com/");}
function ApolloSaveTool(){ window.open("https://mega.nz/folder/SQoCgZYa#5ewTMuQiPFuQuiZP-mdgBw");}
function ApolloSaveToolWeb(){ window.open("https://github.com/bucanero/apollo-ps4");}
function PS4Toolset(){ window.open("https://mega.nz/folder/idQgwKhJ#moz8CqvVtYTsuwO6COK3DQ");}
function PS4ToolsetWeb(){ window.open("https://pkg-zone.com/details/SAAT29385");}
function HomebrewStore(){ window.open("https://mega.nz/folder/eJpSwCKD#KbFKaDHlWpYf71vIf7sXYw");}
function HomebrewStoreWeb(){ window.open("https://github.com/LightningMods/PS4-Store");}
function RemotePKGinstaller(){ window.open("https://mega.nz/folder/WJwDwB4Y#0o4acWIFm-Gg-4qNlPh6mA");}
function RemotePKGinstallerPC(){ window.open("https://mega.nz/folder/jRJwRZyL#KPqSrHbXO6aUmY2fC6Z41g");}
function RemotePKGinstallerWeb(){ window.open("https://github.com/BenjaminFaal/ps4-remote-pkg-installer");}
function PS4XPLORER(){ window.open("https://mega.nz/folder/XJAxgQwJ#gF6-LOj1zgtsFx_uLwYgNA");}
function PS4XPLORERWeb(){ window.open("https://pkg-zone.com/details/LAPY20009");}
function GoldHENCHEATSManagerPKG(){ window.open("https://mega.nz/folder/XJAxgQwJ#gF6-LOj1zgtsFx_uLwYgNA");}
function GoldHENCHEATSManagerPKGWeb(){ window.open("https://github.com/GoldHEN/GoldHEN_Cheat_Manager/releases");}
function GoldHENCHEATSchronoss09(){ window.open("https://mega.nz/folder/Tc5EjAhb#5fgqaSxksQYLAPuzl7TPhQ");}
function GoldHENCHEATSchronoss09Web(){ window.open("https://github.com/chronoss09/GoldHen-Cheats-PKG/releases/tag/v29.04.24");}
function GoldHENCHEATSchronoss09AntiguoWeb(){ window.open("https://github.com/chronoss09/GoldHen-Cheats-PKG/releases/tag/cheat_ps4");}
function GoldCheatsUpdaterPC(){ window.open("https://mega.nz/folder/7IJnmKLY#RzmFLnPF3KvsH84mQiRedQ");}
function GoldCheatsUpdaterPCWeb(){ window.open("https://github.com/Nazky/GoldCheats-Updater/releases");}
function GoldHENCHEATSBD(){ window.open("https://mega.nz/folder/2YBmkbaJ#1X9zzAoCoLeMmZi1ULTscw");}
function GoldHENCHEATSBDWeb(){ window.open("https://github.com/kmeps4/PS4OfflineTrainer");}
function Patches(){ window.open("https://mega.nz/folder/2c4VCKSR#1ZMjYPPqswZsCKk8ilXjuA");}
function PatchesWeb(){ window.open("https://github.com/GoldHEN/GoldHEN_Patch_Repository");}
function GoldHENCheatsPS2(){ window.open("https://mega.nz/folder/6QRzHB5J#lqiU9CcHTJfEhEy8Y7ieAg");}
function GoldHENCheatsPS2Web(){ window.open("https://github.com/chronoss09/GoldHen-Cheats-PKG/releases");}
function GoldHENCheatsPlugins(){ window.open("https://mega.nz/folder/OIgQhbZb#ua8uLZElrAulUJy1HdzK5A");}
function GoldHENCheatsPluginsWeb(){ window.open("https://github.com/GoldHEN/GoldHEN_Plugins_Repository/releases");}
function OrbisToolbox(){ window.open("https://mega.nz/folder/aEhDgCBZ#8zx9zvrUqLtqjDObjZAUaw");}
function OrbisToolboxWeb(){ window.open("https://github.com/OSM-Made/Orbis-Toolbox");}
function ItemzflowGameManager(){ window.open("https://mega.nz/folder/vRIUkByT#A0q5mbqyyOC9vSu_vsJyiQ");}
function ItemzflowGameManagerWeb(){ window.open("https://github.com/LightningMods/Itemzflow");}
function Consolepedia3D(){ window.open("https://mega.nz/folder/TE4klQjK#dc7PsDQrUSqqki3Cwm79IQ");}
function Consolepedia3DWeb(){ window.open("https://github.com/VitaHEX-Games/Consolepedia-3D");}
function WebDAVClient(){ window.open("https://mega.nz/folder/qM5FlDwb#630Zlj1D0PQWbw_WpkPL5A");}
function WebDAVClientWeb(){ window.open("https://github.com/cy33hc/ps4-ezremote-client");}
function Dufs(){ window.open("https://mega.nz/folder/SZRHlaAS#rizl21jQwB28HJVodcGw6Q");}
function DufsWeb(){ window.open("https://github.com/sigoden/dufs/releases");}
function MEGAcmd(){ window.open("https://mega.nz/folder/jIIWCIgZ#H79e52j3u2-7c-jxtpC3lA");}
function MEGAcmdWeb(){ window.open("https://mega.io/es/cmd");}
function LinuxGentooMega(){ window.open("https://mega.nz/folder/mII2WL4J#0Vr8csPNUbpSDVAHeTwSbA");}
function LinuxGentooMedi(){ window.open("https://www.mediafire.com/file/6bdd067gx8koblk/ps4gentoo01-2020.img.gz/file");}
function PayloadInjectorPS4(){ window.open("Payload Injector");}
function PayloadInjectorWeb(){ window.open("https://github.com/TheWizWikii/PS4-Payload-Injector-Tool/releases");}
function Batocera(){ window.open("https://mega.nz/folder/KNZF2agT#-YxENz8fPfoDWXzzzWrgvQ");}
function BatoceraIMG(){ window.open("https://t.me/+x-84XxF06kcxZDEy");}
function BatoceraWeb(){ window.open("https://nuclearhacks.es/como-instalar-batocera-en-ps4-con-pocos-pasos/");}
function FPKGi(){ window.open("https://mega.nz/folder/7ARDzQDR#mVKLpYxZLZn-VhOb3LrZ8g");}
function FPKGiWeb(){ window.open("https://github.com/ItsJokerZz/FPKGi");}
function GAMEBATO(){ window.open("https://mega.nz/folder/KQZnDAKA#f1RPWqBmJcrh-7D8WlT8cw");}
function GAMEBATOWeb(){ window.open("https://gamebatoapp.ir/home/en/");}
function PS4Controller(){ window.open("https://mega.nz/folder/7ZYwxBZQ#tSjxXuG0yr4W9tSD70AhHA");}
function PS4ControllerWeb(){ window.open("https://pkg-zone.com/details/NPXX51364");}
function OnlineLan(){ window.open("https://mega.nz/folder/KFIAgRSb#ChmPYoYYhiWprmxDPpaUVw");}
function OnlineLanWeb(){ window.open("https://discord.com/invite/u8tcA6HpbK");}
function Flash0NORDump(){ window.open("https://mega.nz/folder/fEQUHLZC#qMQczn7Th83OXzBpUtzswQ");}
function Flash0NORDumpWeb(){ window.open("https://github.com/Andryshik345/ps4-sflash0-dumper");}
function AllNotificaciones(){ window.open("https://mega.nz/folder/fVoWgJhT#sUNdOW6bfSaUi19kx7GWVQ");}
function AvatarChanger(){ window.open("https://mega.nz/folder/OQg3hJZI#LZSA10JkQPK5GSvGm9WyZg");}
function AvatarChangerWeb(){ window.open("https://pkg-zone.com/details/LAPY20015");}
//Multimedia
function Plataformas(){ window.open("https://mega.nz/folder/GEgmwZ5J#PXLsE7kwb0H6P7ZUuELWwQ");}
function pPlay(){ window.open("https://mega.nz/folder/TQhCGLiZ#QShhZeCqqXKq_Ot-F49Cxg");}
function pPlayWeb(){ window.open("https://github.com/Cpasjuste/pplay/releases");}
function MediaPlayes(){ window.open("https://mega.nz/folder/yFhQiCaK#RunmCNZTDaQ2mpU7JLTHlQ");}
function MediaPlayesWeb(){ window.open("https://pkg-zone.com/details/CUSA02012");}
function PS4Player(){ window.open("https://mega.nz/folder/LIIThBrD#XUkiajJUrtafEVK7br3iQQ");}
function PS4PlayerWeb(){ window.open("https://pkg-zone.com/details/LAPY20002");}
function PlutoTV(){ window.open("https://mega.nz/folder/CNRyQAAD#ot_Yd97EgbmtRnd6blHAWA");}
function PlutoTVWeb(){ window.open("https://pkg-zone.com/details/CUSA04688");}
function PlataformasMulti(){ window.open("https://mega.nz/folder/TQ5WxTJI#Ly82kGyP2cJs6mTrArcX5w");}
function PlataformasMultiWeb(){ window.open("https://pkg-zone.com/?category=media&console&q");}
//Juegos Retro
function PNES(){ window.open("https://mega.nz/folder/7JQkiZpA#c98AXWgNpETUWqNmdP1cMg");}
function PSNES(){ window.open("https://mega.nz/folder/7JQkiZpA#c98AXWgNpETUWqNmdP1cMg");}
function pfbneo(){ window.open("https://mega.nz/folder/HUxT3agT#JRFqqBfaEEvjn9x3mTO5eA");}
function pgen(){ window.open("https://mega.nz/folder/HUxT3agT#JRFqqBfaEEvjn9x3mTO5eA");}
function pemuWeb(){ window.open("https://github.com/Cpasjuste/pemu");}
function P8(){ window.open("https://mega.nz/folder/HUoCBDzK#BwSruE0_5HU6wlOqTvAf7A");}
function P8Web(){ window.open("https://github.com/voliva/ps4-p8");}
function SNESTicles(){ window.open("https://mega.nz/folder/eVg21RCZ#BvDQUHedChsy4-vBuxb7vA");}
function SNESTiclesWeb(){ window.open("https://github.com/tmaul/SNESticle");}
function RetroArch(){ window.open("https://mega.nz/folder/2dhFVQIJ#IBrx8LY1l0klzSylwzuu-Q");}
function RetroArchWeb(){ window.open("https://www.retroarch.com/?page=platforms");}
//Aplicaciones PC
function CrearAvatarAuto(){ window.open("https://mega.nz/folder/DcQQzLIT#nSZuv43B-kTJPLVBs8xvzA");}
function CrearAvatarManual(){ window.open("https://mega.nz/folder/DBxFGJJC#Mi1xJixDs5EDfeqvJrtC5g");}
function SEGASATURN(){ window.open("https://mega.nz/folder/aMQUDBjT#t8kcfOAYpjZzOIKqbP5dZA");}
function SEGASATURNWeb(){ window.open("https://www.psx-place.com/threads/update-v1-2-saturn-fpkg-convert-saturn-games-into-ps4-fpkgs.36031/");}
function CrearTrucos(){ window.open("https://mega.nz/folder/LA4RkbAJ#6uSdFAdu7-GUXknH9q-6uA");}
function EnvíaarchivosPKG(){ window.open("https://mega.nz/folder/CI4jVQSb#rAUvb2zzjFwhJj24tFcOig");}
function EnvíaarchivosPKGWeb(){ window.open("https://github.com/Gkiokan/ps4-remote-pkg-sender/releases");}
function RestaurarJuegos(){ window.open("https://mega.nz/folder/uUpRlapL#TCLZb4qqMdg_U2h4rpAqMw");}
function PARAMSFOEditor(){ window.open("https://mega.nz/folder/nd5zVL5B#FGrW1us2UIyvtVzwVpEqxQ");}
function PARAMSFOEditorWeb(){ window.open("https://github.com/xXxTheDarkprogramerxXx/PS3Tools/releases/tag/V1.2-SFO");}
function Dumpsjuegos(){ window.open("https://mega.nz/folder/2MYViAbS#W5tzR01GP44eoU0tsDpmdg");}
function DumpsjuegosWeb(){ window.open("https://github.com/hippie68/ftpdump");}
function DumpsjuegosWeb2(){ window.open("https://github.com/CyB1K/PS4-Fake-PKG-Tools-3.87");}
function CreaAccesosDirecto(){ window.open("https://mega.nz/folder/DMBCzILQ#dGzMdVWS_jgAz8EJdY-FJg");}
function CreaAccesosDirectoWeb(){ window.open("https://sqlitebrowser.org/");}
function CrearPSXyPSP(){ window.open("https://mega.nz/folder/LIZRjazC#Y3j6zVdm7zgjx6LW_cqL6Q");}
function CrearPSPWeb(){ window.open("https://github.com/John-K/pspdecrypt/releases");}
function CrearPS1Web(){ window.open("https://www.logic-sunrise.com/news-1162226-ps4-psx-2-ps4-v10-vos-iso-ps1-sur-ps4.html");}
function RemoteconStore(){ window.open("https://mega.nz/folder/DJgU2LiA#hwAQrNVUWyse4eEOdCqD-w");}
function RemoteconStoreWeb(){ window.open("https://github.com/LightningMods/Store-CDN-Tool");}
function TrofeosencriptadosparaPKG(){ window.open("https://mega.nz/folder/nd4gRIqJ#CsFjcfBCBL_B050SF0G-Uw");}
function pkgmerge(){ window.open("https://mega.nz/folder/KN5DGAzL#mmVXvdF0yUhuOYL9fy3N9A");}
function pkgmergeWeb(){ window.open("https://github.com/Tustin/pkg-merge");}
function PS4PKGViewer(){ window.open("https://mega.nz/folder/Gdw0BSAI#3IMjJqr__cF4fYVpq-WG1A");}
function Chiaki(){ window.open("https://mega.nz/folder/rQRgEIbB#rbmAbavJBvGSM0YIl5rWAw");}
function ChiakiWeb(){ window.open("https://git.sr.ht/~thestr4ng3r/chiaki/refs");}
function PSNAccountIDWeb(){ window.open("https://psn.flipscreen.games/");}
function chiakiAppAndroid(){ window.open("https://play.google.com/store/apps/details?id=com.gameblabla.chiaki");}
function PS2FPKG(){ window.open("https://mega.nz/folder/6dJjATTS#SGYyrs4xSji7TRDaMWLzmg");}
function PS2FPKGWeb(){ window.open("https://www.psx-place.com/threads/release-ps2-fpkg-v0-7-beta-a-complete-rewrite-of-my-ps2-to-ps4-converter.41916/");}
function PS2CompatWeb(){ window.open("https://www.psdevwiki.com/ps4/PS2_Classics_Emulator_Compatibility_List");}
function PSPFPKG(){ window.open("https://mega.nz/folder/vJpnBYiT#JdXGRVcyzNAqn3V-tkQpWQ");}
function PSPFPKGWeb(){ window.open("https://www.psx-place.com/threads/psp-fpkg-v1-0-1-play-psp-games-with-the-ps-plus-emulator.37947/");}
function SaturnPS4(){ window.open("https://mega.nz/folder/CNRBXaIZ#D3FntUm2znBCEyv3cvh-qw");}
function SaturnPS4Web(){ window.open("https://www.logic-sunrise.com/news-1172671-ps4-saturn2ps4-v10-pour-505-672-et-900.html");}
function MODSPCPS4(){ window.open("https://mega.nz/folder/yZAVjQhb#O2TllGUBDLEf_GPJU1v4fQ");}
function MODSPCPS4REPAKWeb(){ window.open("https://github.com/Backporter/RE-PAK/releases/tag/5.3");}
function MODSPCPS4RETEXWeb(){ window.open("https://github.com/Backporter/PS4-RE-TEX/releases");}
function MODSPCPS4GoldHENPWeb(){ window.open("https://github.com/GoldHEN/GoldHEN_Plugins_Repository/releases");}
function psx2ps4(){ window.open("https://mega.nz/folder/jBY1yTZY#i0k6MntKrBc7SmgDmfUUEw");}
function psx2ps4Web(){ window.open("https://www.logic-sunrise.com/news-1177662-ps4-psx2ps4-v151-nouvel-emulateur-et-ajout-du-multi-discs.html");}
function PSXFPKG(){ window.open("https://mega.nz/folder/eQAlmbJR#IcWX9FBERw5Eqh691FuvzQ");}
function PSXFPKGWeb(){ window.open("https://www.psx-place.com/threads/psx-fpkg-by-jabu-a-tool-to-convert-ps1-psx-games-for-use-on-ps4.30498/");}
function PS2CodeBreaker(){ window.open("https://mega.nz/folder/jAJHHQKI#586fnLo36TI7eUSSi9N2yw");}
function RetroarchPS2enPS4(){ window.open("https://mega.nz/folder/fIIwAa4J#k5wx0qTa9YGYrKtqILAi0Q");}
function RetroarchPS2enPS4Web(){ window.open("https://www.logic-sunrise.com/news-1175709-ps4-creer-un-fpkg-demulateur-en-un-clic.html");}
function PS4PKGTool(){ window.open("https://mega.nz/folder/Hc5iQL7I#6PeLoNywopih0i_wawqbJQ");}
function PS4PKGToolWeb(){ window.open("https://github.com/pearlxcore/PS4-PKG-Tool?tab=readme-ov-file");}
function TrophyUnlocker(){ window.open("https://mega.nz/folder/fBI2iZJK#9ShHdozeziyA5dXfY2RWMg");}
function TrophyUnlockerWeb(){ window.open("https://github.com/xXxTheDarkprogramerxXx/PS4_Tools/tree/master/TrophyUnlocker");}
//Solucion
function RestaurarJuegos(){ window.open("https://mega.nz/folder/bBRCHLDC#f5Jvla-dFcJ6PZExRjU41A");}
function RestaurarJuegosWeb(){ window.open("https://github.com/aizenar/PS4_db_Rebuilder_EXT");}
function Backupfpkg(){ window.open("https://mega.nz/folder/aBQk2JiA#1TFWt0tbjsXX1uPncHANew");}
function CambiarIconos(){ window.open("https://mega.nz/folder/7YB1XbCK#NvyhHrt7dg_Q7oJvUZO4lQ");}
function CambiarIconosWeb(){ window.open("https://github.com/OfficialAhmed/Iconit-PS4");}



function nombre(){ window.open("");}
function Web(){ window.open("");}


