function KMSToolsPortable(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rFRBBYSQ#Ai2iaeBl0YYTKvgxo4SYRw");}
function KMSToolsPortableOfi(){verificarSesionYAbrirEnlace("http://forum.ru-board.com/topic.cgi?forum=2&amp;topic=5559#1");}
function ActivarWinCMD(){verificarSesionYAbrirEnlace("../Ayuda/ActivarWindows.html#actWin10");}
function Dropbox(){verificarSesionYAbrirEnlace("https://mega.nz/folder/7UAFBYKL#DzDnMqELjSwhujhh_kYShg");}
function DropboxWeb(){verificarSesionYAbrirEnlace("https://www.dropbox.com/install");}
function GoogleDrive(){verificarSesionYAbrirEnlace("https://mega.nz/folder/mJBznIZa#_qSvkbH70CdgOy6FmyZP9g");}
function GoogleDriveWeb(){verificarSesionYAbrirEnlace("https://www.google.com/intl/es/drive/download/");}
function MEGAsync(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bNA1gQ6b#E14pPSKaWZIg_P--wlgpYw");}
function MEGAsyncWeb(){verificarSesionYAbrirEnlace("https://mega.nz/sync");}
function Zippyshare(){verificarSesionYAbrirEnlace("https://mega.nz/folder/CR5VTDBT#OtRZNdOMNalsWQ_7Z5v_GA");}
function ZippyshareWeb(){verificarSesionYAbrirEnlace("https://www.zippyshare.com/sites/uploader.jsp");}
function RaiDrive(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bNR3WQoJ#w_dTxcKXlM10wxUdwhOFAg");}
function RaiDriveWeb(){verificarSesionYAbrirEnlace("https://www.raidrive.com/");}
function AirCluster(){verificarSesionYAbrirEnlace("https://mega.nz/folder/aYJAUCxL#MoQ9IUxwBnmcw5s4A4Axyg");}
function AirClusterWeb(){verificarSesionYAbrirEnlace("https://www.aircluster.org/es/");}
function AirExplorer(){verificarSesionYAbrirEnlace("https://mega.nz/folder/ucYnHa5K#hZhujhxcn7hDeuNrrLGQJQ");}
function AirExplorerWeb(){verificarSesionYAbrirEnlace("https://www.airexplorer.net/es/");}
function AOMEIBackupper(){verificarSesionYAbrirEnlace("https://mega.nz/folder/CcJhQA4a#3iAb8NN-qMQGI96SSD7lrg");}
function AOMEIBackupperWeb(){verificarSesionYAbrirEnlace("https://www.ubackup.com/");}
function CobianSoft(){verificarSesionYAbrirEnlace("https://mega.nz/folder/mBQRwCKY#U2fcvue2GTs0U2sMTzQ_vA");}
function CobianSoftWeb(){verificarSesionYAbrirEnlace("https://www.cobiansoft.com/cobianbackup.html");}
function EaseUSTodoBackupFree(){verificarSesionYAbrirEnlace("https://mega.nz/folder/7MITQCCT#cVee_GTZvZkushSPh_Umgg");}
function EaseUSTodoBackupFreeWeb(){verificarSesionYAbrirEnlace("https://es.easeus.com/landing/newsletter-download.html?tbfree");}
function Java(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fJZXWCLC#K9mPPI4SGeoT3K8kb5-DiA");}
function JavaWeb(){verificarSesionYAbrirEnlace("https://www.java.com/es/download/ie_manual.jsp");}
function JavaJDK(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rBYFACKD#zLYOunH-i5_9BwO5mV9IGQ");}
function JavaJDKWeb(){verificarSesionYAbrirEnlace("https://www.oracle.com/java/technologies/downloads/");}
function WindowsPhotoViewer(){verificarSesionYAbrirEnlace("https://mega.nz/file/ucJTXCzZ#-0iQOHNBVt9erfTDPxHh8WFIJRdOaDFI8kW7kbOkqfE");}
function DS4Windows(){verificarSesionYAbrirEnlace("https://mega.nz/folder/SEZ2XZZD#qR9hUaL-yoa8KGOq_-ivxw");}
function DS4WindowsWeb(){verificarSesionYAbrirEnlace("https://ds4-windows.com/");}
function Zip(){verificarSesionYAbrirEnlace("https://mega.nz/folder/eYIxXYQB#kr0YIlok0Gr0Ugz2abp5Tw");}
function ZipWeb(){verificarSesionYAbrirEnlace("https://www.7-zip.org/download.html");}
function WinRAR(){verificarSesionYAbrirEnlace("https://mega.nz/folder/HJZFVaTY#i11X8W_QdZdue4WBxsrSZg");}
function WinRARWeb(){verificarSesionYAbrirEnlace("https://www.winrar.es/descargas");}
function JDownloader(){verificarSesionYAbrirEnlace("https://mega.nz/folder/qYYnUQ6a#rv36xbQyzOgOsHdMfQnIdQ");}
function JDownloaderWeb(){verificarSesionYAbrirEnlace("https://jdownloader.org/download/index");}
function Mipony(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fdZTFAxA#QKMqDBZ7t4PlJEelClzUTQ");}
function MiponyWeb(){verificarSesionYAbrirEnlace("https://www.mipony.net/es/descarga/");}
function qBittorrent(){verificarSesionYAbrirEnlace("https://mega.nz/folder/jUIzhIKQ#jAfrJh_BUENItwwq598TBQ");}
function qBittorrentWeb(){verificarSesionYAbrirEnlace("https://www.qbittorrent.org/download.php");}
function uTorrent(){verificarSesionYAbrirEnlace("https://mega.nz/folder/nZJTSIIL#fOK9JBWfSx9-rwcdoY6JKg");}
function uTorrentWeb(){verificarSesionYAbrirEnlace("https://www.utorrent.com/intl/es/downloads/win/");}
function Discord(){verificarSesionYAbrirEnlace("https://mega.nz/folder/jNBnHAJS#QxPEPWS1Fa_T5oNXCvfEOQ");}
function DiscordWeb(){verificarSesionYAbrirEnlace("https://discord.com/download");}
function Telegram(){verificarSesionYAbrirEnlace("https://mega.nz/folder/DFRFQQBB#0TiaPHTXFV2zgSsY2bZd8w");}
function TelegramWeb(){verificarSesionYAbrirEnlace("https://desktop.telegram.org/");}
function WhatsAppWeb(){verificarSesionYAbrirEnlace("ms-windows-store://pdp/?productid=9NKSQGP7F2NH&mode=mini");}
function Zoom(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bFI3CQ6I#Q9DbVaoEdySgR07IIl9JOw");}
function ZoomWeb(){verificarSesionYAbrirEnlace("https://zoom.us/download");}
function Firefox(){verificarSesionYAbrirEnlace("https://mega.nz/folder/WQRhlC6D#Y7XDEKRbZk9vrNrF0akMIg");}
function FirefoxWeb(){verificarSesionYAbrirEnlace("https://www.mozilla.org/es-CL/firefox/new/");}
function GoogleChrome(){verificarSesionYAbrirEnlace("https://mega.nz/folder/7cY3zQDS#OwWYaHff6tTAEnsIIjyYBw");}
function GoogleChromeWeb(){verificarSesionYAbrirEnlace("https://www.google.com/chrome/?hl=es&brand=CHMI");}
function Opera(){verificarSesionYAbrirEnlace("https://mega.nz/folder/LFIDGCjZ#_hvPfwAaz0p6oHW7sEOK5Q");}
function OperaWeb(){verificarSesionYAbrirEnlace("https://www.opera.com/es/download");}
function Chromium(){verificarSesionYAbrirEnlace("https://mega.nz/folder/HNwQHYTI#NRJAhqDaHwCdx4Llj1mygw");}
function ChromiumWeb(){verificarSesionYAbrirEnlace("https://chromium.woolyss.com/download/es/");}
function AdobeAcrobatReaderDC(){verificarSesionYAbrirEnlace("https://mega.nz/folder/KNYDCIYL#T71amoZb28MtC2Vvf2Af2Q");}
function AdobeAcrobatReaderDCWeb(){verificarSesionYAbrirEnlace("https://get.adobe.com/es/reader/");}
function Office2019(){verificarSesionYAbrirEnlace("https://mega.nz/folder/GJYjwCQR#QakgI08cEXky0Yjmw6Io2Q");}
function AIMP(){verificarSesionYAbrirEnlace("https://mega.nz/folder/LYQnTITa#mGbse40qi-NhFfyZnoawYw");}
function AIMPWeb(){verificarSesionYAbrirEnlace("https://www.aimp.ru/?do=download");}
function VLCmediaplayer(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bBJBXKpL#9mOYSUKra5OAl1o15Kij7w");}
function VLCmediaplayerWeb(){verificarSesionYAbrirEnlace("https://www.videolan.org/vlc/");}
function CCleaner(){verificarSesionYAbrirEnlace("https://mega.nz/folder/PAIx1Iab#_9YXhygUa_JzQDn2HIEUvQ");}
function CCleanerWeb(){verificarSesionYAbrirEnlace("https://www.ccleaner.com/es-es/ccleaner/download");}
function TeamViewer(){verificarSesionYAbrirEnlace("https://mega.nz/folder/DRRRDAhI#EQOIMv7iG847To4SDZOMpg");}
function TeamViewerWeb(){verificarSesionYAbrirEnlace("https://www.teamviewer.com/en-us/download/windows/");}
function VirtualBox(){verificarSesionYAbrirEnlace("https://mega.nz/folder/TcAlSCDB#Hg8TteWvcvBj2oV_i4N2Ug");}
function VirtualBoxWeb(){verificarSesionYAbrirEnlace("https://www.virtualbox.org/wiki/Downloads");}
function HDDLowLevelFormatTool(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fRBh3L4R#6nFtCLJao9UaM3g-KSEsqw");}
function HDDLowLevelFormatToolWeb(){verificarSesionYAbrirEnlace("https://hddguru.com/software/HDD-LLF-Low-Level-Format-Tool/");}
function USBWRITEPROTECTOR(){verificarSesionYAbrirEnlace("https://mega.nz/folder/GZwT0AyK#NOJoFgL0YrOp_-HdvBuD8Q");}
function OBSStudio(){verificarSesionYAbrirEnlace("https://mega.nz/folder/HUYjTZJb#UWddxXxeQQX_GReES91mqg");}
function OBSStudioWeb(){verificarSesionYAbrirEnlace("https://obsproject.com/es/download");}
function Photoshop2021(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fQ4EHBQR#thCms8BPmNQhrT5ZbFz5_w");}
function Photoshop2021Web(){verificarSesionYAbrirEnlace("https://www.adobe.com/cl/products/photoshop.html");}
function ApowerREC(){verificarSesionYAbrirEnlace("https://mega.nz/folder/CcQDlJbD#BnQzx04TOBDVBj_Fdpflxg");}
function ApowerRECWeb(){verificarSesionYAbrirEnlace("https://www.apowersoft.es/record-all-screen");}
function Battle(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bMBWWAQY#_svkjqlgw_OkT8btGo3tHg");}
function BattleWeb(){verificarSesionYAbrirEnlace("https://www.blizzard.com/es-es/download/");}
function Origin(){verificarSesionYAbrirEnlace("https://mega.nz/folder/LI5DgaAQ#BSEzoFALIpflTMFLBeYSZA");}
function OriginWeb(){verificarSesionYAbrirEnlace("https://www.origin.com/chl/es-es/store/download");}
function Steam(){verificarSesionYAbrirEnlace("https://mega.nz/folder/ScA0GaTB#J02RLsJucvaI8FzBj17n6w");}
function SteamWeb(){verificarSesionYAbrirEnlace("https://store.steampowered.com/about/");}
function EmuladoresPC(){verificarSesionYAbrirEnlace("../Tutoriales/PC/EmuladoresPC.html");}
function DMarkProfessionalEdition(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fRIFEa7B#A97ORUe-lWcTK0S5UVp_cQ");}
function DMarkProfessionalEditionWeb(){verificarSesionYAbrirEnlace("https://benchmarks.ul.com/download");}
function AIDA64Extreme(){verificarSesionYAbrirEnlace("https://mega.nz/folder/eUZSSJbR#_-KfKFPnFxEPN3PRx98jvA");}
function AIDA64ExtremeWeb(){verificarSesionYAbrirEnlace("https://www.aida64.com/downloads");}
function CINEBENCH(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rZBwDDIS#Xuj5_5xQjekGj9WkD7aINw");}
function CINEBENCHWeb(){verificarSesionYAbrirEnlace("https://www.maxon.net/en/downloads");}
function CoreTemp(){verificarSesionYAbrirEnlace("https://mega.nz/folder/6cgTUKSL#y972SBZzNx8WCU_kMYwIEw");}
function CoreTempWeb(){verificarSesionYAbrirEnlace("https://www.alcpu.com/CoreTemp/");}
function CPUIDHWMonitor(){verificarSesionYAbrirEnlace("https://mega.nz/folder/zdp1mYJA#d3u56nh2K-lTQ1y1lOxPcg");}
function CPUZ(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rNAhkTIZ#8pvbm4i7zjtS_0Kws_mDhQ");}
function CPUZWeb(){verificarSesionYAbrirEnlace("https://www.cpuid.com/softwares/cpu-z.html");}
function CrystalDiskInfo(){verificarSesionYAbrirEnlace("https://mega.nz/folder/vA4gWaCS#2tROY_ktfmK7r3si6coQmw");}
function CrystalDiskInfoWeb(){verificarSesionYAbrirEnlace("https://crystalmark.info/en/software/crystaldiskinfo/");}
function HWiNFO(){verificarSesionYAbrirEnlace("https://mega.nz/folder/nVI1zIpY#_E7W-RsxnvAkVQPV9DU5cA");}
function HWiNFOWeb(){verificarSesionYAbrirEnlace("https://www.hwinfo.com/download/");}
function MemTest64(){verificarSesionYAbrirEnlace("https://mega.nz/folder/HdBjRQTC#U6Eu4DWmQDzuwbnLS6vfDQ");}
function PassMarkPerformanceTest(){verificarSesionYAbrirEnlace("https://mega.nz/folder/DZBBzKTB#CSgFtN36tb9cDFR1gi98mQ");}
function PassMarkPerformanceTestWeb(){verificarSesionYAbrirEnlace("https://www.passmark.com/products/performancetest/download.php");}
function PCMark(){verificarSesionYAbrirEnlace("https://mega.nz/folder/GV5ElCzS#XGuIUqg6x0CvJWKIkN8CHA");}
function PCMarkWeb(){verificarSesionYAbrirEnlace("https://benchmarks.ul.com/3dmark");}
function Prime95(){verificarSesionYAbrirEnlace("https://mega.nz/folder/LYYmiBBZ#WlVqpb-PwKtjCX38bLL2vg");}
function RealTemp(){verificarSesionYAbrirEnlace("https://mega.nz/folder/WQhjxQLQ#j2oSvuRgrN_lyw8t1Dc29A");}
function Monitor11(){verificarSesionYAbrirEnlace("https://mega.nz/file/SVQRGD6S#pSeZiUocFYkSHO4tCKnmK6U7WdA0YuJlG4sf3vfBvQY");}
function Speccy(){verificarSesionYAbrirEnlace("https://mega.nz/folder/ORYlBS4b#2_qEyQpTLAzLdt9iIYpoEg");}
function SpeccyWeb(){verificarSesionYAbrirEnlace("https://www.ccleaner.com/speccy?cc-noredirect=");}
function AdobeDreamweaver(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rRIXHLIa#EPNx-rh-ZPSbI-PmfX0mfw");}
function AdobeDreamweaverWeb(){verificarSesionYAbrirEnlace("https://www.adobe.com/cl/products/dreamweaver.html");}
function AndroidStudio(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bQBAzBKb#-PSk1EOl1q9spYTLYtq56Q");}
function AndroidStudioWeb(){verificarSesionYAbrirEnlace("https://developer.android.com/studio");}
function FileZilla(){verificarSesionYAbrirEnlace("https://mega.nz/folder/mYBjHYQK#pcLiJemv3EN_1ON0OToT4g");}
function FileZillaWeb(){verificarSesionYAbrirEnlace("https://filezilla-project.org/download.php");}
function Fork(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rARBiR4A#dMasu3KrLJua9dldXcF7Fg");}
function ForkWeb(){verificarSesionYAbrirEnlace("https://git-fork.com/");}
function GitHubDesktop(){verificarSesionYAbrirEnlace("https://mega.nz/folder/SRBiEBbR#kEbQeaVPriIxZItdTtxAyg");}
function GitHubDesktopWeb(){verificarSesionYAbrirEnlace("https://desktop.github.com/");}
function NetBeans(){verificarSesionYAbrirEnlace("https://mega.nz/folder/vN4wEAhL#AoruzHtpvixbsz6u4knCig");}
function NetBeansWeb(){verificarSesionYAbrirEnlace("https://netbeans.apache.org/");}
function Notepad(){verificarSesionYAbrirEnlace("https://mega.nz/folder/eMQx0AjL#QThAPkHBIA4xrQ_FG_ZG9w");}
function NotepadWeb(){verificarSesionYAbrirEnlace("https://notepad-plus-plus.org/downloads/");}
function PSeInt(){verificarSesionYAbrirEnlace("https://mega.nz/folder/jZpggJjZ#sshPJMsup2o5zjvAC0fLdQ");}
function PSeIntWeb(){verificarSesionYAbrirEnlace("http://pseint.sourceforge.net/");}
function VisualStudio(){verificarSesionYAbrirEnlace("https://mega.nz/folder/XBRnmCoT#L6fVArjFmxEuwdglb6zTGw");}
function VisualStudioWeb(){verificarSesionYAbrirEnlace("https://visualstudio.microsoft.com/es/downloads/");}
function VisualStudioCode(){verificarSesionYAbrirEnlace("https://mega.nz/folder/jQYCHRpK#6VF6FSWtIte3aB8Mr8fckw");}
function VisualStudioCodeWeb(){verificarSesionYAbrirEnlace("https://code.visualstudio.com/");}
function xampp(){verificarSesionYAbrirEnlace("https://mega.nz/folder/2VIi1ALB#0_AGGMZ981uHnozR3GGLbQ");}
function xamppWeb(){verificarSesionYAbrirEnlace("https://www.apachefriends.org/es/index.html");}

function BlueStacks(){verificarSesionYAbrirEnlace("https://mega.nz/folder/KMhWHbKa#fW9Bll8YgNGokkyrKtUHIA");}
function BlueStacksWeb(){verificarSesionYAbrirEnlace("https://www.bluestacks.com/es/index.html");}
function Dolphin(){verificarSesionYAbrirEnlace("https://mega.nz/folder/uFRzCBDZ#iXeixoUmC27plT0msXx-eQ");}
function DolphinWeb(){verificarSesionYAbrirEnlace("https://es.dolphin-emu.org/?cr=es");}
function WhineCube(){verificarSesionYAbrirEnlace("https://mega.nz/folder/3NIhGSCK#kcGMYp7ugyPM1le3M1Repw");}
function WhineCubeWeb(){verificarSesionYAbrirEnlace("http://whinecube.emulation64.com/");}
function GBEnhanced(){verificarSesionYAbrirEnlace("https://mega.nz/folder/yAJG0LIB#kx-IiadplHlMuJV7banFaQ");}
function GBEnhancedWeb(){verificarSesionYAbrirEnlace("https://github.com/shonumi/gbe-plus");}
function Mednafen(){verificarSesionYAbrirEnlace("https://mega.nz/folder/PIpFkDjA#0BfafyciWx6CrxdFQ8OUhw");}
function MednafenWeb(){verificarSesionYAbrirEnlace("https://mednafen.github.io/");}
function mGBA(){verificarSesionYAbrirEnlace("https://mega.nz/folder/yFpRkZRJ#96nEzVRb0ROkhs6qurzKyw");}
function mGBAWeb(){verificarSesionYAbrirEnlace("https://mgba.io/");}
function VisualBoyAdvance(){verificarSesionYAbrirEnlace("https://mega.nz/folder/iNQ3za4Z#dpn9wDl-hIncrTmemWePLA");}
function VisualBoyAdvanceWeb(){verificarSesionYAbrirEnlace("https://www.emulator-zone.com/doc.php/gba/vboyadvance.html");}
function CXBX(){verificarSesionYAbrirEnlace("https://mega.nz/folder/7YpnRDQZ#pftfCAKalzUUyeo0cF09uw");}
function CXBXWeb(){verificarSesionYAbrirEnlace("http://www.caustik.com/cxbx/download.htm");}
function DXBX(){verificarSesionYAbrirEnlace("https://mega.nz/folder/WBw1VLzD#6XCqLlqdxut0Wr-pWGDKlQ");}
function DXBXWeb(){verificarSesionYAbrirEnlace("https://sourceforge.net/projects/dxbx/");}
function Xenia(){verificarSesionYAbrirEnlace("https://mega.nz/folder/XZglGRoD#Vkwq_-EzJGF03_LwXv7_tQ");}
function XeniaWeb(){verificarSesionYAbrirEnlace("https://xenia.jp/");}
function Citra(){verificarSesionYAbrirEnlace("https://mega.nz/folder/mFpTFL7J#0aM83y3iAJR4NBySrFMhlQ");}
function CitraWeb(){verificarSesionYAbrirEnlace("https://citra-emu.org/");}
function Project64(){verificarSesionYAbrirEnlace("https://mega.nz/folder/GQg3RQRK#pqUAg6TUQeBJvvv0aX7plg");}
function Project64Web(){verificarSesionYAbrirEnlace("https://www.pj64-emu.com/windows-downloads");}
function NintendoNum(){verificarSesionYAbrirEnlace("https://mega.nz/folder/DABHUbQD#Q0ysCvDS59aaLSPuDvwR1Q");}
function NintendoNumWeb(){verificarSesionYAbrirEnlace("https://sourceforge.net/projects/schibo/");}
function Mupen64Plus(){verificarSesionYAbrirEnlace("https://mega.nz/folder/mBAiAIZL#PJFmXsXYk7dlq-Nt-IvQow");}
function Mupen64PlusWeb(){verificarSesionYAbrirEnlace("http://www.mupen64plus.org/");}
function FCEUX(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bNBRRaCS#4m_4iTj2F0SBkcJESv59VQ");}
function FCEUXWeb(){verificarSesionYAbrirEnlace("https://fceux.com/web/home.html");}
function Jnes(){verificarSesionYAbrirEnlace("https://mega.nz/folder/KZwV2TpK#CVSA0kLCRR7tdf2DL42LRA");}
function JnesWeb(){verificarSesionYAbrirEnlace("http://www.jabosoft.com/categories/1");}
function Nestopia(){verificarSesionYAbrirEnlace("https://mega.nz/folder/7QgxSQSR#q4B3uZJRIF2oouDIYgTluw");}
function NestopiaWeb(){verificarSesionYAbrirEnlace("http://nestopia.sourceforge.net/");}
function VirtuaNES(){verificarSesionYAbrirEnlace("https://mega.nz/folder/qEgmybDA#KX0lIGv1ZXROAzUdvEYgwQ");}
function VirtuaNESWeb(){verificarSesionYAbrirEnlace("http://virtuanes.s1.xrea.com/");}
function Ryujinx(){verificarSesionYAbrirEnlace("https://mega.nz/folder/XIAEBCBT#WXuG2Gwobyz-MDVGON-sEA");}
function RyujinxWeb(){verificarSesionYAbrirEnlace("https://ryujinx.org/download/");}
function Yuzu(){verificarSesionYAbrirEnlace("https://mega.nz/folder/XRZy0ICA#d6msPMjYpFLx3L49_IgLEw");}
function YuzuWeb(){verificarSesionYAbrirEnlace("https://yuzu-emu.org/");}
function Dolphin(){verificarSesionYAbrirEnlace("https://mega.nz/folder/aYQHgSpA#2SlA5yehi6ZVRuLS7c4t7A");}
function DolphinWeb(){verificarSesionYAbrirEnlace("https://es.dolphin-emu.org/?cr=es");}
function CEMU(){verificarSesionYAbrirEnlace("https://mega.nz/folder/aFwQ2ToY#iabZ-D-sqR1sHtAXMcdjvw");}
function CEMUWeb(){verificarSesionYAbrirEnlace("https://cemu.info/");}
function ePSXe(){verificarSesionYAbrirEnlace("https://mega.nz/folder/jNYW2JjS#lwqpwjRgzRGxLohg6pVw5w");}
function ePSXeWeb(){verificarSesionYAbrirEnlace("https://www.epsxe.com/download.php");}
function PCSX2(){verificarSesionYAbrirEnlace("https://mega.nz/folder/KAJm1I4K#Gw3ZhgPwp0DP4FCU_XUMCQ");}
function PCSX2Web(){verificarSesionYAbrirEnlace("https://pcsx2.net/downloads/");}
function EmulatorX(){verificarSesionYAbrirEnlace("https://mega.nz/folder/DEJ0wDQZ#hqa9QXcBkm0iiVm95Y35lw");}
function EmulatorXWeb(){verificarSesionYAbrirEnlace("https://sourceforge.net/projects/emulatorx/");}
function RPCS3(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fExQXbgD#_SDIfyWKX2SfM0Pu1MHNiA");}
function RPCS3Web(){verificarSesionYAbrirEnlace("https://rpcs3.net/download");}
function ESXEmulator(){verificarSesionYAbrirEnlace("https://mega.nz/folder/yMB0zRTT#JyuM4xBKTTpW11795sNBww");}
function ESXEmulatorWeb(){verificarSesionYAbrirEnlace("https://esxemulator.com/");}
function PSSPP(){verificarSesionYAbrirEnlace("https://mega.nz/folder/XdADhZCS#OwyoiWhUmovP-4Ulvhoqhw");}
function PSSPPWeb(){verificarSesionYAbrirEnlace("https://www.ppsspp.org/downloads.html");}
function JPCSP(){verificarSesionYAbrirEnlace("https://mega.nz/folder/eMgDTIAS#1LSX6ZdByFwNh1pTg2CYgA");}
function JPCSPWeb(){verificarSesionYAbrirEnlace("https://jpcsp.org/");}
function Bizhawk(){verificarSesionYAbrirEnlace("https://mega.nz/folder/XRw3FaIY#VqWVa6FhLCcZxmBy4Y-m-w");}
function BizhawkWeb(){verificarSesionYAbrirEnlace("https://tasvideos.org/Bizhawk");}
function Snes9x(){verificarSesionYAbrirEnlace("https://mega.nz/folder/eZ5HVBia#p3_E1ae75SNlOz_TjitxPQ");}
function Snes9xWeb(){verificarSesionYAbrirEnlace("https://www.zophar.net/snes/snes9x.html");}
function RetroArch(){verificarSesionYAbrirEnlace("https://mega.nz/folder/TUoHUbRZ#WozjHVnJ6QO9AhU2NirQag");}
function RetroArchWeb(){verificarSesionYAbrirEnlace("https://www.retroarch.com/");}
function AutorunsAutorunsc(){verificarSesionYAbrirEnlace("https://mega.nz/folder/rdZG1SZZ#OcOL5C48u1d3lvAJXckZ7g");}
function AutorunsAutorunscWeb(){verificarSesionYAbrirEnlace("https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns");}
function ReinicioDetalladoWindows(){verificarSesionYAbrirEnlace("https://mega.nz/file/nVRkQSAK#TSgXL_NNm_gnTyqfDViYZXMKkf_Q1OsEkCQs-6BP0Tc");}
function KLiteCodecPackMega(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fQ5DULJa#z3vo7I9apPuCRuw7aH6OUA");}
function KLiteCodecPackMegaWeb(){verificarSesionYAbrirEnlace("https://codecguide.com/download_k-lite_codec_pack_mega.htm");}
function PlexAPP(){verificarSesionYAbrirEnlace("https://mega.nz/folder/WZ4TSLLA#b8RFiAmkKyKsPFokVwUEBA");}
function PlexAPPWeb(){verificarSesionYAbrirEnlace("https://www.plex.tv/media-server-downloads/?lang=es&cat=plex+desktop&plat=windows#plex-app");}
function PlexServerWeb(){verificarSesionYAbrirEnlace("https://apps.microsoft.com/detail/plex-media-server/XPFM11Z0W10R7G?hl=es-es&gl=US");}
function RETROBAT(){verificarSesionYAbrirEnlace("https://mega.nz/folder/fQQnwCDY#TwHe7wcFD7ME6zadlkHp9A");}
function RETROBATWeb(){verificarSesionYAbrirEnlace("https://www.retrobat.org/descargar/");}
function AdvancedIPScanner(){verificarSesionYAbrirEnlace("https://mega.nz/folder/LRowTKzI#9VXzlDiuGpToIJ0zi0Xeaw");}
function AdvancedIPScannerWeb(){verificarSesionYAbrirEnlace("https://www.advanced-ip-scanner.com/es/");}
function FreeFileSync(){verificarSesionYAbrirEnlace("https://mega.nz/folder/LNwnjYST#t26SrwCt0xUpV56xc94kkg");}
function FreeFileSyncWeb(){verificarSesionYAbrirEnlace("https://freefilesync.org/download.php");}
function MousewithoutBorders(){verificarSesionYAbrirEnlace("https://mega.nz/folder/iIAimASQ#cwZuUCmsbTIrzb5Otb_epg");}
function MousewithoutBordersWeb(){verificarSesionYAbrirEnlace("https://www.microsoft.com/en-us/download/details.aspx?id=35460");}
function PCHealthCheck(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bIhDTRBB#goOH2am-l9_foxYoh3vF-A");}
function PCHealthCheckWeb(){verificarSesionYAbrirEnlace("https://aka.ms/GetPCHealthCheckApp");}
function ProcessExplorer(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bIhDTRBB#goOH2am-l9_foxYoh3vF-A");}
function ProcessExplorerWeb(){verificarSesionYAbrirEnlace("https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer");}
function UpdateWinXPa82012(){verificarSesionYAbrirEnlace("https://mega.nz/folder/GAwDkTQC#ZrLg_ijKd3djIKc067PDdw");}
function UpdateWinXPa82012Web(){verificarSesionYAbrirEnlace("https://legacyupdate.net/");}
function WinDirStat(){verificarSesionYAbrirEnlace("https://mega.nz/folder/aMgkBDqI#9wdhLGlV9fZWWBGCykbGww");}
function WinDirStatWeb(){verificarSesionYAbrirEnlace("https://windirstat.net/");}
function UltraISO(){verificarSesionYAbrirEnlace("https://mega.nz/folder/bBBlAByK#Ka2AUgfCnTM4bkM_XKIIug");}
function UltraISOWeb(){verificarSesionYAbrirEnlace("https://www.ultraiso.com/download.html");}
function GUIFORMAT(){verificarSesionYAbrirEnlace("https://mega.nz/folder/ydZgQTYA#8C4MbbOHlwYjTYTQQdUtkA");}
function GUIFORMATWeb(){verificarSesionYAbrirEnlace("http://ridgecrop.co.uk/index.htm?guiformat.htm");}


function nombre(){verificarSesionYAbrirEnlace("");}
function Web(){verificarSesionYAbrirEnlace("");}



function verificarSesionYAbrirEnlace(enlace) {
    if (sessionStorage.length > 0) {
        // Hay una sesión activa
        window.open(enlace);
    } else {
        iniciarSesion();
    }}

function iniciarSesion() {
    var resultado = window.confirm('Sesión no iniciada.\n¿Desea iniciar sesión?');
    if (resultado === true) {
        window.alert('Ingrese los datos a continuación');
        window.location.href = '../Login.html';
    } else {
        window.alert('Sesión no iniciada');
    }}
